arubanetworks/meridian-web-sdk

CHANGELOG.md, src/web-sdk.tsx
Note: We'll still need to deploy this manually after it's merged
=> more documentation

CHANGELOG.md, TESTING.md, demo/option-toggles/index.html, demo/option-toggles/style.css, src/Map.js, src/PlacemarkLayer.js, src/web-sdk.tsx
=> MR-365 add option to disable loading placemarks

CHANGELOG.md, src/PlacemarkLayer.js
I updated the changelog to follow the [Keep a Changelog](https://keepachangelog.com/en/1.0.0/) specification, since it makes your changelog easier to read and maintain
=> MR-246 ignore exclusion zones

.travis.yml, CHANGELOG.md, src/Map.js, src/Overlay.js
=> MR-369 adds support for changing locationID

docs-readme.md, package-lock.json, src/web-sdk.tsx
=> add devCloud to envOptions, write a blurb about require.resolve in docs

.gitignore
=> add cypress gitignores

demo/cypress/basic/index.html
=> remove code not part of test

cypress/integration/filter-by-id.spec.ts, demo/cypress/filter-by-id/index.html
=> MR-627 Cypress filter by ID

cypress/integration/filter-by-name.spec.ts, demo/cypress/filter-by-name/index.html
=> MR-623 adds filter by name test

cypress/integration/control-tags.spec.ts, demo/cypress/control-tags/index.html
=> MR-626 control tag test

CHANGELOG.md, src/Map.js
=> MR-640, load /update placemarks after changing floors (regression)

CHANGELOG.md, demo/basic/index.html, src/Map.js
=> Mr 460 post test fix

CHANGELOG.md, src/FloorOverlay.js
=> MR-642 hide unpublished floors

cypress/integration/basic.spec.ts, cypress/integration/control-tags.spec.ts, cypress/integration/load-placemarks.spec.ts, demo/cypress/control-tags/index.html, demo/cypress/load-placemarks/index.html
=> Mr 641 load placemarks

cypress/integration/filter-by-tag-label.spec.ts, cypress/integration/filter-update.spec.ts, cypress/integration/not-shown-placemarks.spec.ts, cypress/integration/util/getMeridianMap.ts
=> Refactor Cypress tests to use getMeridianMap as a util file

pull_request_template.md
=> New testing proposal

cypress/integration/control-tags.spec.ts
=> control-tags test update

cypress/integration/filter-by-placemark-types.spec.ts
=> MR-668 Adds placemarks.filter Cypress test

cypress/integration/tag-search.spec.ts, demo/cypress/tag-search/index.html, src/TagListOverlay.js
=> MR-667 Adds Cypress tag search test

CHANGELOG.md, demo/cypress/utils/fake-api.js, demo/full-page/index.html, src/Map.js, src/util.ts, src/web-sdk.tsx
=> MR-685 Use custom HTTP header; refactor MeridianSDK.API

DEVELOPMENT.md, cypress/integration/tag-response.spec.ts
=> cypress real data tag-response test

CHANGELOG.md, cypress/integration/tag-response.spec.ts, demo/basic/index.html, demo/shared.css, package-lock.json, package.json, src/web-sdk.tsx
=> MR-853 Add .destroy method

CHANGELOG.md, cypress/integration/auto-destroy.spec.ts, demo/basic/index.html, demo/shared.css, src/Map.js, src/TagLayer.js, src/web-sdk.tsx
=> MR-865 auto-destroy

demo/marker-click/index.html
=> MR-815 fix marker-click demo

CHANGELOG.md, cypress/integration/overlays-polygon.spec.ts, cypress/integration/overlays-polyline.spec.ts, demo/cypress/polyline/index.html, demo/index.html, demo/overlay-polygon/index.html, demo/overlay-polyline/index.html, src/OverlayLayer.tsx, src/OverlayPolygon.tsx, src/OverlayPolyline.tsx, src/web-sdk.tsx
=> MR-971 overlay polyline

demo/index.html, demo/overlay-area/index.html, demo/overlay-polyline-from-directions-api/index.html, demo/overlay-polyline/index.html, package-lock.json, package.json
=> Demo and package updates

CHANGELOG.md, cypress/integration/annotations-point.spec.ts, demo/annotation-point/index.html, demo/cypress/annotation-point/index.html, demo/index.html, demo/overlay-polygon/index.html, src/AnnotationLayer.tsx, src/AnnotationPoint.tsx, src/Map.js, src/OverlayPolygon.tsx, src/OverlayPolyline.tsx, src/Placemark.js, src/style.js, src/web-sdk.tsx
=> MR-803 custom annotations

CHANGELOG.md, cypress/integration/load-placemarks.spec.ts, cypress/integration/load-tags.spec.ts, demo/cypress/load-tags/index.html, demo/location-viewer/index.html, demo/option-toggles/index.html, src/Map.js, src/TagLayer.js, src/web-sdk.tsx
=> MR-1019 no asset tracking

CHANGELOG.md, src/AnnotationLayer.tsx, src/MapComponent.tsx, src/OverlayLayer.tsx, src/PlacemarkLayer.tsx, src/Tag.tsx, src/TagLayer.tsx
=> MR-1047 fix layers

demo/tag-label/index.html, demo/tag-labels/index.html, demo/tag-name/index.html
Make sure to turn off whitespace diff; I ran prettier on these files which changed almost all the indentation.
=> MR-1042 fixes broken demos again

CHANGELOG.md, cypress/integration/placemark-label-mode.spec.ts, demo/option-toggles/index.html, demo/option-toggles/style.css, src/MapComponent.tsx, src/Placemark.tsx, src/PlacemarkLayer.tsx, src/web-sdk.tsx
=> MR-1077 placemark label display modes

demo/index.html, demo/placemark-label-zoom-level/index.html
=> Update Placemark Label Zoom Level Demo, Hide directions demo

demo/cypress/utils/mock-maps.js, package-lock.json, package.json
This is a partial update of packages, 0 vulnerabilities as of today.
=> MR-1143 Package Updates

CHANGELOG.md, src/MapComponent.tsx
=> MR-1136 Dynamic default zoom and map centering

src/MapComponent.tsx
=> MR-1136 Default Zoom tweak (nudge map up)

src/MapComponent.tsx, src/web-sdk.tsx
=> MR-1146 d3 zoom event fix

CHANGELOG.md, src/MapComponent.tsx
=> Mr 1117 limit panning

demo/index.html, demo/load-tags/index.html
=> MR-1168 Add loadTags demo

CHANGELOG.md, src/OverlayLayer.tsx
=> MR-1185 chrome browser zoom annotation layer bug

CHANGELOG.md, demo/annotation-point/index.html, demo/overlay-polygon/index.html, src/AnnotationPoint.tsx, src/OverlayLayer.tsx, src/OverlayPolygon.tsx, src/web-sdk.tsx
=> MR-1221 add overlay click handlers

CHANGELOG.md, src/Placemark.tsx
=> MR-1235 Label Placemark display fix

package-lock.json, package.json, src/style.ts
=> MR-1125 CSS, upgrade emotionjs

src/AnnotationPoint.tsx
=> MRC-1171 AnnotationPoints, add centering rule

package-lock.json, package.json
➜ npm audit
found 0 vulnerabilities
=> MRC-1399 package updates and audits

CHANGELOG.md, src/MapComponent.tsx
=> MRC-1090 Placemark Search, re-fetch all placemarks every 8 minutes

CHANGELOG.md, demo/directions-overview/index.html, demo/index.html, src/web-sdk.tsx
=> MRC-1469 Directions Overview demo, pre release mods

CHANGELOG.md, src/AssetListOverlay.tsx
=> MRC-1484 fix a bug related to unnamed Placemarks and the Asset List Overlay

CHANGELOG.md, demo/cypress/utils/mock-all-assets.js, demo/cypress/utils/mock-placemarks.js, package-lock.json, package.json, src/AssetListOverlay.tsx
=> MRC-1486 Asset List, Handle tags without names

package-lock.json, package.json
=> MRC-1423 remove deprecated querystring pkg, resoled by package updates(cypress)

CHANGELOG.md, demo/index.html, demo/openStreamZone/index.html, src/web-sdk.tsx
=> MRC-1517 openStream, add resource options

.travis.yml, CHANGELOG.md, DEVELOPMENT.md
=> update language to main

CHANGELOG.md, demo/annotation-kiosk/index.html, demo/index.html
useful in the instance of kiosk usage
=> Add demo to illustrate adding "you are here" to a map

CHANGELOG.md, demo/directions-overview/index.html, demo/overlay-polygon/index.html, demo/overlay-polyline/index.html, src/OverlayPolygon.tsx, src/OverlayPolyline.tsx, src/web-sdk.tsx
=> MRC-1561 SVG Overlays, add additional props for styling

CHANGELOG.md, src/AssetListOverlay.tsx
=> MRC-1577 SearchOverlay, align radio buttons with labels

CHANGELOG.md, package-lock.json
=> MRC-1610 async package update

CHANGELOG.md, src/DetailsOverlay.tsx
=> MRC-1636 Details Overlay, update no name placemark output

CHANGELOG.md, src/MapComponent.tsx
=> MRC-1725 Remove pan limiting (translateExtent) related code

CHANGELOG.md, src/LoadingSpinner.tsx, src/MapComponent.tsx, src/PlacemarkLayer.tsx, src/TagLayer.tsx
=> MRC-1742 Fetch SearchOverlay assets after floor assets have loaded

CHANGELOG.md, src/MapComponent.tsx
=> MRC-1808 Init change to prevent possible race condition

CHANGELOG.md, demo/cypress/utils/fake-api.js, demo/openStream/index.html, demo/openStreamZone/index.html, src/TagLayer.tsx, src/web-sdk.tsx
=> MRC-1814 Fixed issue where tags that have left the floor after initialization could still appear on the map

CHANGELOG.md, src/AssetListOverlay.tsx
=> MRC-1617 i18 support, added additional UI translations

CHANGELOG.md, demo/cypress/utils/mock-all-assets.js, src/AssetListOverlay.tsx, src/FloorOverlay.tsx, src/MapComponent.tsx, src/Translations.tsx, src/web-sdk.tsx
=> MRC-1892 i18 - allow setting language manually, doc updates

package-lock.json, package.json
=> MRC-1916 Package updates and Security audit

package-lock.json
=> MRC-2207 Security Audit, update dns-packet

CHANGELOG.md, README.md, demo/index.html
=> MRC-2151 Added messaging that indicates the WebSDK is not a complete location services SDK.

CHANGELOG.md, src/web-sdk.tsx
=> MRC-1308 Ad blocker fix, use new endpoints without "track" in the URL

CHANGELOG.md, package-lock.json, package.json
https://github.com/advisories/GHSA-hc6q-2mpp-qw7j
=> MRC-2239 Security Audit - update Webpack

.prettierignore, CHANGELOG.md, src/web-sdk.tsx
=> MRC-2256 Fix broken API method fetchFloorData

CHANGELOG.md, src/web-sdk.tsx
=> MRC-2282 Switch to previous BE endpoints (revert MRC-1308)

CHANGELOG.md, src/web-sdk.tsx
=> MRC-2292 Switch to new BE endpoints (restore MRC-1308)

CHANGELOG.md, demo/max-zoom/index.html, demo/min-zoom/index.html, src/MapComponent.tsx, src/web-sdk.tsx
=> MRC-2276 Pan/Zoom - set default values and customization of zoom levels

demo/index.html
=> MRC-2276 Zoom limits, add links to new demos

src/MapComponent.tsx
=> MRC-2276 Pan Extents - make padding dynamic

CHANGELOG.md, src/MapComponent.tsx, src/web-sdk.tsx
=> MRC-2276 Pan Extent mods, add centerMap method

CHANGELOG.md, demo/index.html, demo/openStreamLocation/index.html, demo/openStreamTag/index.html, demo/openStreamTagLabel/index.html, demo/openStreamZone/index.html, src/web-sdk.tsx
=> MRC-2325 api.openStream() updates

CHANGELOG.md, src/web-sdk.tsx
=> MRC-2323 Expose Tag Details API

CHANGELOG.md, demo/center-map/index.html, demo/index.html, demo/zoom-to-default/index.html, demo/zoom-to-point/index.html, src/web-sdk.tsx
=> MRC-2605 Demos, add examples for zoomToDefault, zoomToPoint and centerMap

CHANGELOG.md, cypress.config.ts, package-lock.json, package.json
=> MRC-2620 Security audit and dependency updates

CHANGELOG.md, src/TagLayer.tsx, src/web-sdk.tsx
=> MRC-2685 Loading spinner mod to ensure spinner shows after changing floors (and disconnecting)

CHANGELOG.md, src/FloorOverlay.tsx, src/MapComponent.tsx, src/web-sdk.tsx
=> MRC-2746 Floor switcher UI, allow descending ordering of floors

package-lock.json, package.json
=> MRC-2815 Security Audit and Package Upgrades

.travis.yml, CHANGELOG.md, package-lock.json, package.json
=> MRC-2948 Security Audit and Package Upgrades

.travis.yml, CHANGELOG.md
=> MRC-2958 CI, deploy update "on" value for node_js to 20

.travis.yml, CHANGELOG.md
https://docs.travis-ci.com/user/deployment-v2
=> MRC-2976 Deployment - Updated travis config to use dpl V2
